name: Documentation Build Test

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Build Documentation

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Install Python dependencies
      run: |
        pip install -r docs/requirements.txt

    - name: Build documentation
      working-directory: docs
      run: |
        make html

    - name: Check for warnings and errors
      working-directory: docs
      run: |
        if [ -f _build/html/index.html ]; then
          echo "Documentation built successfully"
          echo "Generated files:"
          ls -la _build/html/
        else
          echo "Documentation build failed - index.html not found"
          exit 1
        fi

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/
        retention-days: 7